# Add configuration values here, as shown below.

# Twitter API
TWITTER_CONSUMER_KEY: "iyCvnDTa32sdIycATny2au12I"
TWITTER_CONSUMER_SECRET: "okITF7m0JA48mAIGUkhpKKlPzwNejymxqtW3GpRj9U2pZuFbjD"
TWITTER_ACCESS_TOKEN: "834841611615866880-fzwEhqhidPk8XLHZ3tAyp2KXklQw8xr"
TWITTER_ACCESS_TOKEN_SECRET: "Hn8O5NrHE1Ggk1pVJ4kX2DqgJPeSX4egOz7mCDd0Teug0"