# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: bitparrot.co
  secret_key_base: adb0be64c096c68b799ee52ec7190d9ee51e6df9f057e23cee9f96cd56a033999bd8ede511f50d37cba28b69a08ae1bbeebeaf3ffdc977c043781e2bab9ff8d1

test:
  export DOMAIN_NAME="bitparrot.co"
#  commenting this as it is showing as creating an error
#  secret_key_base: 03f14ebf058a8bab549ad92c64df21b74de692bc522ac77075ceb39f6cc343920b1c9bd88cccefdf2f7c17ae91786c61bdb93e7a1d855134488561ca93ce7282

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
